name: Continuous Integration

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...
